#!/usr/bin/env python3
"""Bake the browser build's actor model trees into C.

Reads the JSON that `node tests/model_ref.js <emberdeep.html>` produces and
writes src/model_data.h and src/model_data.c. The geometry is therefore the
browser's own scene graph rather than a hand transcription of it.

    tools/gen_models.py <models.json> <src-dir>
"""
import json
import re
import sys

GEO = {'Box': 'GEO_BOX', 'Cylinder': 'GEO_CYLINDER', 'Cone': 'GEO_CONE',
       'Sphere': 'GEO_SPHERE', 'Torus': 'GEO_TORUS', 'Plane': 'GEO_PLANE',
       'Icosahedron': 'GEO_ICOSA'}
SURF = {'floorStone': 'SURF_FLOOR_STONE', 'wallMason': 'SURF_WALL_MASON',
        'rock': 'SURF_ROCK', 'bone': 'SURF_BONE', 'cloth': 'SURF_CLOTH',
        'leather': 'SURF_LEATHER', 'metal': 'SURF_METAL', 'wood': 'SURF_WOOD',
        'skin': 'SURF_SKIN', 'hide': 'SURF_HIDE'}
KIND = {'biped': 'MKIND_BIPED', 'arachnid': 'MKIND_ARACHNID',
        'quad': 'MKIND_QUAD', 'float': 'MKIND_FLOAT'}

FIXED_JOINTS = {'body': 'JOINT_BODY', 'chest': 'JOINT_CHEST',
                'headPivot': 'JOINT_HEAD', 'tail': 'JOINT_TAIL',
                'cape0': 'JOINT_CAPE0', 'wing0': 'JOINT_WING0',
                'wing1': 'JOINT_WING1',
                'armR_s': 'JOINT_ARMR_S', 'armR_e': 'JOINT_ARMR_E',
                'armR_h': 'JOINT_ARMR_H', 'armL_s': 'JOINT_ARML_S',
                'armL_e': 'JOINT_ARML_E', 'armL_h': 'JOINT_ARML_H'}
LEG_RE = re.compile(r'^leg(\d+)_([hk])$')


def joint_of(name):
    if not name:
        return 'JOINT_NONE'
    if name in FIXED_JOINTS:
        return FIXED_JOINTS[name]
    m = LEG_RE.match(name)
    if m:
        i, part = int(m.group(1)), m.group(2)
        return 'JOINT_LEG_HIP(%d)' % i if part == 'h' else 'JOINT_LEG_KNEE(%d)' % i
    return 'JOINT_NONE'


def f(v):
    if v is None or v is False:
        return '0'
    if v is True:
        return '1'
    v = float(v)
    if v == int(v) and abs(v) < 1e7:
        return '%d' % int(v)
    return '%.9gf' % v


def ident(name):
    return 'MODEL_' + re.sub(r'[^A-Za-z0-9]', '_', name).upper()


def main():
    if len(sys.argv) < 3:
        print(__doc__)
        return 2
    models = json.load(open(sys.argv[1]))
    out = sys.argv[2].rstrip('/')

    banner = ('/* Generated by tools/gen_models.py from the browser build\'s own\n'
              '   scene graphs - do not edit by hand. Regenerate with:\n'
              '     node tests/model_ref.js emberdeep.html > models.json\n'
              '     tools/gen_models.py models.json src            */\n')

    with open(out + '/model_data.h', 'w') as h:
        h.write(banner)
        h.write('#ifndef EMBERDEEP_MODEL_DATA_H\n#define EMBERDEEP_MODEL_DATA_H\n\n')
        h.write('enum {\n')
        for m in models:
            h.write('    %s,\n' % ident(m['name']))
        h.write('    MODEL_COUNT\n};\n\n')
        h.write('/* defined in model.h, which includes this file */\n')
        h.write('extern const struct ModelDefTag kModels[MODEL_COUNT];\n\n')
        h.write('#endif\n')

    with open(out + '/model_data.c', 'w') as c:
        c.write(banner)
        c.write('#include "model.h"\n\n')
        total = 0
        for m in models:
            nodes = m['nodes']
            total += len(nodes)
            c.write('/* %s: %d nodes, %d meshes */\n'
                    % (m['name'], len(nodes), m['partCount']))
            c.write('static const ModelNode k%s[] = {\n' % ident(m['name']).title())
            for n in nodes:
                params = list(n.get('params') or [])
                params += [0] * (8 - len(params))
                c.write('    { %d, %s, %s, %s,\n'
                        % (n['parent'], joint_of(n['name']),
                           GEO.get(n.get('geom'), '-1'),
                           SURF.get(n.get('surf'), '-1')))
                col = n.get('col')
                rgb = ((col >> 16) & 255, (col >> 8) & 255, col & 255) \
                    if isinstance(col, int) else (255, 255, 255)
                c.write('      { %s }, { %s }, { %s },\n'
                        % (', '.join(f(v) for v in n['pos']),
                           ', '.join(f(v) for v in n['rot']),
                           ', '.join(f(v) for v in n['scale'])))
                c.write('      { %s },\n'
                        % ', '.join('%.6ff' % (v / 255.0) for v in rgb))
                c.write('      { %s } },\n' % ', '.join(f(v) for v in params[:8]))
            c.write('};\n\n')

        c.write('const ModelDef kModels[MODEL_COUNT] = {\n')
        for m in models:
            legs = len(m['joints'].get('legs', []))
            mask = []
            for n in m['nodes']:
                j = joint_of(n['name'])
                if j != 'JOINT_NONE':
                    mask.append('(1u << %s)' % j)
            expr = ' | '.join(sorted(set(mask))) or '0u'
            c.write('    { "%s", %s, %d, %d,\n      %s,\n      k%s },\n'
                    % (m['name'], KIND.get(m['kind'], 'MKIND_BIPED'), legs,
                       len(m['nodes']), expr, ident(m['name']).title()))
        c.write('};\n')

    print('wrote %s/model_data.{h,c}: %d models, %d nodes'
          % (out, len(models), total))
    return 0


if __name__ == '__main__':
    sys.exit(main())
