/* Generated by tools/gen_models.py from the browser build's own
   scene graphs - do not edit by hand. Regenerate with:
     node tests/model_ref.js emberdeep.html > models.json
     tools/gen_models.py models.json src            */
#ifndef EMBERDEEP_MODEL_DATA_H
#define EMBERDEEP_MODEL_DATA_H

enum {
    MODEL_VANGUARD,
    MODEL_PYROMANCER,
    MODEL_RANGER,
    MODEL_GOBLIN,
    MODEL_ARCHER,
    MODEL_SPIDER,
    MODEL_SKELETON,
    MODEL_WRAITH,
    MODEL_HOUND,
    MODEL_IMP,
    MODEL_GOLEM,
    MODEL_WARCHIEF,
    MODEL_COLOSSUS,
    MODEL_WARDEN,
    MODEL_COUNT
};

/* defined in model.h, which includes this file */
extern const struct ModelDefTag kModels[MODEL_COUNT];

#endif
